### ISSUE TITLE
下载视频顺序调整

### ISSUE THREAD

**Issue by bottomash** [lifegpc/bili#102]
现在的视频下载模式是从最新的下载到最旧的一个。会产生一个**文件创建时间顺序和视频收藏顺序不一致**的情况。例如视频1是最新收藏的视频，视频2是第二新的视频；现在的逻辑是先下载视频1，然后下载视频2 ，就造成文件的创建时间视频2是晚于视频1的创建时间。
能不能给出一个选项先下载视频2，然后下载视频1的选项，使得文件创建时间与收藏顺序一致？

**Comment by lifegpc** [comment]
``
python -m pip install -r requirements.txt
``

**Comment by lifegpc** [comment]
你可以使用pwsh来修改时间，其实发布时间是写入视频元数据的
