### ISSUE TITLE
似乎Chrome Driver不支持88之后的版本

### ISSUE THREAD

**Issue by EricZhang615** [lifegpc/bili#103]
命令行模式下登陆账号，Chrome的窗口弹出之后立刻闪退，但是在命令行模式下可以继续从命令行登录，log文件提示
```
This version of ChromeDriver only supports Chrome version 88
Current browser version is 92.0.4515.159 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
```

除此之外在挂着clash代理的时候，拉取不到最新版本号，之后下载登录时也会立刻闪退，关闭代理后问题解决，log文件也附在下面了
[AV847663419_1630210456.log](https://github.com/lifegpc/bili/files/7071923/AV847663419_1630210456.log)

**Comment by lifegpc** [comment]
Clash会导致python requests BUG。
请加上 `--nte` 参数或者手动设置HTTP_PROXY和HTTPS_PTOXY的环境变量
Chrome那个更新到同版本的chromedriver即可，或者可以使用Firefox的geckodriver

**Comment by lifegpc** [comment]
> 请加上 `--nte` 参数

设置里有一个“requests是否使用环境变量中的代理设置”，选否即可
