### ISSUE TITLE
@lifegpc 我觉得这个强依赖可以用requests 替代的

### ISSUE THREAD

**Issue by PlexPt** [lifegpc/bili#13]
@lifegpc 我觉得这个强依赖可以用requests 替代的

_Originally posted by @PlexPt in https://github.com/lifegpc/bili/issues/11#issuecomment-642378676_

基于CNN卷积神经网络的验证码识别
由Hsury提供
https://github.com/Hsury/Bilibili-Toolkit

**Comment by lifegpc** [comment]
已经看到了。
等考试周过去再写（
到时候作为chrome不可用情况下的备用登录方式

**Comment by lifegpc** [comment]
#18 已完成

**Comment by PlexPt** [comment]
#18 整合环境包呢

**Comment by lifegpc** [comment]
https://github.com/lifegpc/bili/releases/tag/v1.1.5

**Comment by lifegpc** [comment]
python的话，跑一下
``` bash
pip3 install --upgrade rsa
```
