### ISSUE TITLE
按范围选择下载视频时报错 KeyError: 'videos'

### ISSUE THREAD

**Issue by orange1423** [lifegpc/bili#26]
系统环境：Linux raspberrypi 5.4.51-v8+ #1327 SMP PREEMPT Thu Jul 23 11:11:34 BST 2020 aarch64 GNU/Linux
Python版本：Python-3.8.5
bili软件版本：[v1.2.4](https://github.com/lifegpc/bili/releases/tag/v1.2.4)
登录的B站账号为月度大会员

命令行输出：

> python3 start.py
    bili  Copyright (C) 2019-2020  lifegpc
    This program comes with ABSOLUTELY NO WARRANTY; for details type `show w'.
    This is free software, and you are welcome to redistribute it
    under certain conditions; type `show c' for details.
    你可以在<https://github.com/lifegpc/bili>上找到源代码。
当前版本：1.2.4(3de329a)
网络错误：无法获取最新稳定版本字符串。
请输入av/ss/ep/md/bv号（BV号请以BV开头）或者链接（支持用户页的收藏夹、频道、投稿、小视频链接，支持直播、直播回放和已购课程视频链接）：（你可以使用","来分隔多个输入。）SS33802
登录校验成功！
ID：28229233
SSID：33802
标题：Re：从零开始的异世界生活 第二季
系列名字：Re：从零开始的异世界生活
描述：我一定会拯救你。
在打倒了魔女教大罪司教「怠惰」担当——培提其乌斯·罗曼尼康帝之后，菜月昴和爱蜜莉雅又得以重新开始。
克服了艰难的诀别，两人终于和解，然而这只是新一轮风波的序幕。
超乎想象的绝境危机，接踵而至的残酷现实。
少年将再次直面残酷的命运。
类型：番剧
发布时间：2020-07-08 23:00:00
内容：
1.第1话
标题：各自的誓言
AV号：626339509
BV号：BV1mt4y1Q74Q
CID:210288241
ID:330798
2.第2话
标题：下一个地方
AV号：498851287
BV号：BV1qK411H7QF
CID:212844570
ID:330799
3.第3话
标题：久候多时的重逢
AV号：328997408
BV号：BV1ZA411a7R7
CID:215462618
ID:330800
4.第4话
标题：亲子
AV号：371612893
BV号：BV1uZ4y1M7Ch
CID:218424302
ID:330801
5.第5话
标题：踏出的一步
AV号：969061597
BV号：BV1np4y1q7Ar
CID:221080169
ID:330802
6.第6话
标题：少女的福音
AV号：201689081
BV号：BV1Yh411d7NS
CID:223703773
ID:330803
PV:
7.正式PV
标题：
AV号：455889505
BV号：BV1r5411p7T9
CID:205208133
ID:329553
8.制作决定PV
标题：
AV号：413575139
BV号：BV1EV411k7Qq
CID:203194650
ID:329552
9.角色PV
标题： 菜月昴篇
AV号：584029176
BV号：BV1tz4y1Q7ZW
CID:218682822
ID:333963
10.角色PV
标题：雷姆篇
AV号：584029176
BV号：BV1tz4y1Q7ZW
CID:218682899
ID:333964
11.角色PV
标题：拉姆篇
AV号：584029176
BV号：BV1tz4y1Q7ZW
CID:218683004
ID:333965
12.角色PV
标题：爱蜜莉雅篇
AV号：584029176
BV号：BV1tz4y1Q7ZW
CID:218683067
ID:333966
请输入你想下载的视频编号（每两个编号间用,隔开，全部下载可输入a，可以使用-分开两个数字以选择一个范围（例如：1-25））：(下载上次观看的EP330798可输入l。)1-6
Traceback (most recent call last):
  File "start.py", line 1589, in <module>
    main(ip)
  File "start.py", line 1478, in main
    if i>0 and i<=data['videos'] and (not (i in cho)):
KeyError: 'videos'

打印报错的变量data：

> {'mediaInfo': {'id': 28229233, 'ssId': 33802, 'title': 'Re：从零开始的异世界生活 第二季', 'jpTitle': '', 'series': 'Re：从零开始的异世界生活', 'alias': '', 'evaluate': '我一定会拯救你。\n在打倒了魔女教大罪司教「怠惰」担当——培提其乌斯·罗曼尼康帝之后，菜月昴和爱蜜莉雅又得以重新开始。\n克服了艰难的诀别，两人终于和解，然而这只是新一轮风波的序幕。\n超乎想象的绝境危机，接踵而至的残酷现实。\n少年将再次直面残酷的命运。', 'type': '番剧', 'time': '2020-07-08 23:00:00', 'cover': 'https://i0.hdslb.com/bfs/bangumi/image/f2425cbdb07cc93bd0d3ba1c0099bfe78f5dc58a.png'}, 'epList': [{'id': 330798, 'aid': 626339509, 'bvid': 'BV1mt4y1Q74Q', 'cid': 210288241, 'titleFormat': '第1话', 'longTitle': '各自的誓言', 'i': 0, 'loaded': False, 'cover': 'https://i0.hdslb.com/bfs/archive/417d16c9ee4d496f69319987d0a26683e651c106.jpg'}, {'id': 330799, 'aid': 498851287, 'bvid': 'BV1qK411H7QF', 'cid': 212844570, 'titleFormat': '第2话', 'longTitle': '下一个地方', 'i': 1, 'loaded': False, 'cover': 'https://i0.hdslb.com/bfs/archive/a9ddf39402010e0432b2c4033a790719752ec187.jpg'}, {'id': 330800, 'aid': 328997408, 'bvid': 'BV1ZA411a7R7', 'cid': 215462618, 'titleFormat': '第3话', 'longTitle': '久候多时的重逢', 'i': 2, 'loaded': False, 'cover': 'https://i0.hdslb.com/bfs/archive/73f7a28a765fe1536295c2e6311b285743f54d9a.jpg'}, {'id': 330801, 'aid': 371612893, 'bvid': 'BV1uZ4y1M7Ch', 'cid': 218424302, 'titleFormat': '第4话', 'longTitle': '亲子', 'i': 3, 'loaded': False, 'cover': 'https://i0.hdslb.com/bfs/archive/e3ace71c46ca99465273c95d4c9848aa6b84260b.jpg'}, {'id': 330802, 'aid': 969061597, 'bvid': 'BV1np4y1q7Ar', 'cid': 221080169, 'titleFormat': '第5话', 'longTitle': '踏出的一步', 'i': 4, 'loaded': False, 'cover': 'https://i0.hdslb.com/bfs/archive/2f5bf4840747fc7c09932d2793e96a178cd05905.jpg'}, {'id': 330803, 'aid': 201689081, 'bvid': 'BV1Yh411d7NS', 'cid': 223703773, 'titleFormat': '第6话', 'longTitle': '少女的福音', 'i': 5, 'loaded': False, 'cover': 'https://i0.hdslb.com/bfs/archive/cd0d822900707dda303bb689bf9fef0326b32d64.jpg'}], 'sections': [{'id': 48655, 'title': 'PV', 'epList': [{'id': 329553, 'aid': 455889505, 'bvid': 'BV1r5411p7T9', 'cid': 205208133, 'titleFormat': '正式PV', 'longTitle': '', 'i': 0, 'loaded': False, 'title': 'PV', 'cover': 'https://i0.hdslb.com/bfs/archive/23578c063dc238524b428f28f9d20087fcbb0be5.jpg'}, {'id': 329552, 'aid': 413575139, 'bvid': 'BV1EV411k7Qq', 'cid': 203194650, 'titleFormat': '制作决定PV', 'longTitle': '', 'i': 1, 'loaded': False, 'title': 'PV', 'cover': 'https://i0.hdslb.com/bfs/archive/e43fe78becc700ca40070dc8e4640d55eac73cb0.jpg'}, {'id': 333963, 'aid': 584029176, 'bvid': 'BV1tz4y1Q7ZW', 'cid': 218682822, 'titleFormat': '角色PV', 'longTitle': ' 菜月昴篇', 'i': 2, 'loaded': False, 'title': 'PV', 'cover': 'https://i0.hdslb.com/bfs/bangumi/8ea1e5e71388c19ef187bb47cb8e5c2fc8e6885d.jpg'}, {'id': 333964, 'aid': 584029176, 'bvid': 'BV1tz4y1Q7ZW', 'cid': 218682899, 'titleFormat': '角色PV', 'longTitle': '雷姆篇', 'i': 3, 'loaded': False, 'title': 'PV', 'cover': 'https://i0.hdslb.com/bfs/bangumi/883f7363071d1cf6982d547798ffa45975834229.jpg'}, {'id': 333965, 'aid': 584029176, 'bvid': 'BV1tz4y1Q7ZW', 'cid': 218683004, 'titleFormat': '角色PV', 'longTitle': '拉姆篇', 'i': 4, 'loaded': False, 'title': 'PV', 'cover': 'https://i0.hdslb.com/bfs/bangumi/05243aa4a00e28ba9aa44d5ac4d948c0070f86c9.jpg'}, {'id': 333966, 'aid': 584029176, 'bvid': 'BV1tz4y1Q7ZW', 'cid': 218683067, 'titleFormat': '角色PV', 'longTitle': '爱蜜莉雅篇', 'i': 5, 'loaded': False, 'title': 'PV', 'cover': 'https://i0.hdslb.com/bfs/bangumi/80480e9032b1dfaf9fd8c754d4f8c31ace8b6c9e.jpg'}]}]}

**Comment by lifegpc** [comment]
饭吃好修，已经知道哪里bug了

**Comment by lifegpc** [comment]
Fixed in 98d1e78.
你可以切换到dev分支
