### ISSUE TITLE
下载报错 AttributeError: 'int' object has no attribute 'replace'

### ISSUE THREAD

**Issue by orange1423** [lifegpc/bili#27]
系统环境：Linux raspberrypi 5.4.51-v8+ #1327 SMP PREEMPT Thu Jul 23 11:11:34 BST 2020 aarch64 GNU/Linux
Python版本：Python-3.8.5
bili软件版本：v1.2.4
登录的B站账号为月度大会员

命令行输出：

> python3 start.py
    bili  Copyright (C) 2019-2020  lifegpc
    This program comes with ABSOLUTELY NO WARRANTY; for details type `show w'.
    This is free software, and you are welcome to redistribute it
    under certain conditions; type `show c' for details.
    你可以在<https://github.com/lifegpc/bili>上找到源代码。
当前版本：1.2.4(3de329a)
网络错误：无法获取最新稳定版本字符串。
请输入av/ss/ep/md/bv号（BV号请以BV开头）或者链接（支持用户页的收藏夹、频道、投稿、小视频链接，支持直播、直播回放和已购课程视频链接）：（你可以使用","来分隔多个输入。）SS33802
登录校验成功！
ID：28229233
SSID：33802
标题：Re：从零开始的异世界生活 第二季
系列名字：Re：从零开始的异世界生活
描述：我一定会拯救你。
在打倒了魔女教大罪司教「怠惰」担当——培提其乌斯·罗曼尼康帝之后，菜月昴和爱蜜莉雅又得以重新开始。
克服了艰难的诀别，两人终于和解，然而这只是新一轮风波的序幕。
超乎想象的绝境危机，接踵而至的残酷现实。
少年将再次直面残酷的命运。
类型：番剧
发布时间：2020-07-08 23:00:00
内容：
1.第1话
标题：各自的誓言
AV号：626339509
BV号：BV1mt4y1Q74Q
CID:210288241
ID:330798
2.第2话
标题：下一个地方
AV号：498851287
BV号：BV1qK411H7QF
CID:212844570
ID:330799
3.第3话
标题：久候多时的重逢
AV号：328997408
BV号：BV1ZA411a7R7
CID:215462618
ID:330800
4.第4话
标题：亲子
AV号：371612893
BV号：BV1uZ4y1M7Ch
CID:218424302
ID:330801
5.第5话
标题：踏出的一步
AV号：969061597
BV号：BV1np4y1q7Ar
CID:221080169
ID:330802
6.第6话
标题：少女的福音
AV号：201689081
BV号：BV1Yh411d7NS
CID:223703773
ID:330803
PV:
7.正式PV
标题：
AV号：455889505
BV号：BV1r5411p7T9
CID:205208133
ID:329553
8.制作决定PV
标题：
AV号：413575139
BV号：BV1EV411k7Qq
CID:203194650
ID:329552
9.角色PV
标题： 菜月昴篇
AV号：584029176
BV号：BV1tz4y1Q7ZW
CID:218682822
ID:333963
10.角色PV
标题：雷姆篇
AV号：584029176
BV号：BV1tz4y1Q7ZW
CID:218682899
ID:333964
11.角色PV
标题：拉姆篇
AV号：584029176
BV号：BV1tz4y1Q7ZW
CID:218683004
ID:333965
12.角色PV
标题：爱蜜莉雅篇
AV号：584029176
BV号：BV1tz4y1Q7ZW
CID:218683067
ID:333966
请输入你想下载的视频编号（每两个编号间用,隔开，全部下载可输入a，可以使用-分开两个数字以选择一个范围（例如：1-25））：(下载上次观看的EP330798可输入l。)1          你选中了第1话,
请输入你要下载的方式：
1.当前弹幕下载
2.全弹幕下载（可能需要大量时间）
3.视频下载
4.当前弹幕+视频下载
5.全弹幕+视频下载
7.仅封面图片下载3
视频轨：
画质：高清 1080P+(1920x1080,23.810(16000/672)fps)
文件大小：375.56M(393806406B,1831.57kbps)
音频轨：
ID：30280
文件大小：66.27M(69485277B,323.17kbps)
正在开始下载第1个文件，共2个文件。
单文件最大5个连接，单个服务器最大3个连接，文件分片大小5M，预分配方式为prealloc
08/13 11:29:47 [NOTICE] Downloading 1 item(s)
08/13 11:29:47 [NOTICE] 正在分配磁盘空间。使用 --file-allocation=none 以禁用此功能。参见 man 手册中的 --file-allocation 以获悉更多详情。
[#7543b3 371MiB/375MiB(98%) CN:2 DL:8.2MiB]                                                                                                                     
08/13 11:30:38 [NOTICE] 下载已完成：/storage/Download/Re：从零开始的异世界生活 第二季(SS33802)/1.各自的誓言(高清 1080P+,avc1.640028).m4s
下载结果：
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
7543b3|OK  |   8.9MiB/s|/storage/Download/Re：从零开始的异世界生活 第二季(SS33802)/1.各自的誓言(高清 1080P+,avc1.640028).m4s
状态标识：
(OK)：下载已完成。
Traceback (most recent call last):
  File "start.py", line 1590, in <module>
    main(ip)
  File "start.py", line 1569, in main
    read=videodownload.epvideodownload(i,"https://www.bilibili.com/bangumi/play/ss%s"%(data['mediaInfo']['ssId']),data,section,cho3,cho5,se,ip,ud)
  File "/home/pi/bili_1.2.4_linux/videodownload.py", line 1611, in epvideodownload
    read=dwaria2(r2,getfn2(i,1,fdir,vqs,hzm,fin),geturll(dash['audio']),dash['audio']['size'],c3,ip,se,2,2,True)
  File "/home/pi/bili_1.2.4_linux/videodownload.py", line 2971, in getfn2
    return f"{f}/{i['i']+1}.{file.filtern(i['longTitle'])}({file.filtern(vqs[i2])}).{hzm[i2]}"
  File "/home/pi/bili_1.2.4_linux/file/filter.py", line 57, in filtern
    filen=filen.replace('/','_')
AttributeError: 'int' object has no attribute 'replace'

打印报错的变量filen：

> 30280

**Comment by orange1423** [comment]
附上settings.json

> {"lan": "zh_CN", "mp": true, "ad": true, "cd": true, "rd": true, "a": true, "sv": false, "o": "/storage/Download/", "in": false}

**Comment by lifegpc** [comment]
Fixed in 3f46c4a
