### ISSUE TITLE
使用用户名和密码登录出现了问题

### ISSUE THREAD

**Issue by kevinxYaoJiu** [lifegpc/bili#29]
使用ChromeDriver登录发生错误，尝试采用用户名、密码登录。
然后我尝试使用用户名和密码登录，却发现用户名输入完成之后，密码死活不给我打，就像是卡输入法了一样，但是我确认了我已经用了英文输入法，就是没法打出来，重启电脑之后再次尝试还是如此。
偷懒不成只能翻墙去下载chromedriver，我的chrome是84版本，下载了对应的文件替换后就可以正常使用了，现在下载体验极佳，作者牛逼
但是不一定所有人都有翻墙的手段，还是希望作者大大能解决一下不能打密码的问题，我不清楚是不是我一个人的问题，但是密码打不出来确实挺奇怪的(感觉就像是死机了一样，反正就是没反应QAQ，但是我的电脑很好肯定不是死机orz)

**Comment by lifegpc** [comment]
那个是关闭回显（由于安全原因，一般都是关闭回显的）了，正常输入后按Enter即可。

**Comment by kevinxYaoJiu** [comment]
原来是这样，受教了，谢谢你
