### ISSUE TITLE
建议增加收藏夹自动按同一种方式下载的功能

### ISSUE THREAD

**Issue by orange1423** [lifegpc/bili#31]
emmmmmm
大概是这样的，
我的收藏夹里有一百多个视频，
于是我就按了一百多次3并回车。
QWQ

**Comment by lifegpc** [comment]
建议上命令行`py start.py -d 下载方式` 或者 `start.exe -d 下载方式`。
命令行的具体说明可以使用 `py start.py -h` 或者 `start.exe -h` 查看。

**Comment by lifegpc** [comment]
小白的话，可以去看看这个：http://sodevel.com/course/res/269/922

**Comment by orange1423** [comment]
明白了，感谢大佬QWQ
