### ISSUE TITLE
无法下载ep类型视频

### ISSUE THREAD

**Issue by 553627045** [lifegpc/bili#34]
无论是电影还是番剧等等ep开头的视频都无法下载。webui显示暂不支持，命令行直接显示下载成功然后消失，然而文件并没有成功下载。
Version:1.2.6.73(8729c60)

**Comment by lifegpc** [comment]
webui还没有写番剧的解析。

**Comment by lifegpc** [comment]
建议新建一个文本文件start.bat
在里面输入
```
start.exe
cmd
```
或者
```
py start.py
cmd
```
然后双击运行start.bat，把输出的错误截图

**Comment by lifegpc** [comment]
我复现了无法下载视频的问题，现在在修。

**Comment by 553627045** [comment]
![8L_DNH28)IFMT5P($9PN( P](https://user-images.githubusercontent.com/37760718/94812626-8f57d380-0429-11eb-8569-5be5843c67e2.png)
![CXFB)5%WDSMGECI %_W2ODS](https://user-images.githubusercontent.com/37760718/94812639-92eb5a80-0429-11eb-8d35-acff04ff4609.png)

**Comment by lifegpc** [comment]
https://github.com/lifegpc/bili/releases/tag/v1.2.6.81
