### ISSUE TITLE
关于文件覆盖，能不能设置默认不覆盖/覆盖。

### ISSUE THREAD

**Issue by lluke2** [lifegpc/bili#35]
如题，文件覆盖能不能设置默认的选项。感觉一个视频点一下，有点太麻烦了。

**Comment by lifegpc** [comment]
这个现在目前只接受命令行指定，可以考虑加设置（等先修完下载BUG再加

**Comment by lifegpc** [comment]
命令行可以使用```py start.py -y```(```start.exe -y```)来默认覆盖，不覆盖为```py start.py -n```(```start.exe -n```)
新的设置下个版本可以加上。:(
命令行的使用可以谷歌或百度。
命令行的帮助可以使用```py start.py -h```(```start.exe -h```)。
