### ISSUE TITLE
建议: 能不能批量选择某一个清晰度的视频下载

### ISSUE THREAD

**Issue by ab503044120** [lifegpc/bili#55]
比如选择720 1080 而不是选择序号,有时候下载某些专辑他内部的视频的清晰度不一样,就会出现一定的匹配问题

**Comment by lifegpc** [comment]
36156e1 和 786be39

**Comment by lifegpc** [comment]
可以使用 `-V 格式ID[编码]` 来选择。
例如 `-V 112` 选择 1080P+的视频轨。如果找不到1080P+，使用比112小的其他id，如果还找不到就使用最高的画质。
如果使用 `-V 112avc` 可以优先选择avc的编码格式。如果找不到或者没有指定，就使用第一个找到的。
