### ISSUE TITLE
-bash: -d: command not found

### ISSUE THREAD

**Issue by orangeff** [lifegpc/bili#57]
- ### 环境1 debian10，python3.7.3
- 输入命令python3 start.py -i https://space.bilibili.com/3904677/favlist?fid=113096677&ftype=create -d 4 -p a --ym --yac --ndm --yad --yr --yf --mc avc --ar --ax 2 --as 5 --ak 20 --ab --fa prealloc --nsv --yma --ms 0 --yna -o /home/download/Bilibili --naf --nslt --nte --nbd --cad --bp --nin --nmt --uc --ass --dmp --vf mkv
返回-bash: -d: command not found后继续读取视频信息，在选择下载的对话框输入a同样返回-bash: a: command not found
`root@debian:/home/download/Bilibili/bili# python3 start.py -i https://space.bilibili.com/3904677/favlist?fid=113096677&ftype=create -d 4 -p a --ym --yac --ndm --yad --yr --yf --mc avc --ar --ax 2 --as 5 --ak 20 --ab --fa prealloc --nsv --yma --ms 0 --yna -o /home/download/Bilibili --naf --nslt --nte --nbd --cad --bp --nin --nmt --uc --ass --dmp --vf mkv [10] 1765
-bash: -d: command not found
root@debian:/home/download/Bilibili/bili#     bili  Copyright (C) 2019-2021  lifegpc
    This program comes with ABSOLUTELY NO WARRANTY; for details type `show w'.
    This is free software, and you are welcome to redistribute it
    under certain conditions; type `show c' for details.
    You can find the source code on <https://github.com/lifegpc/bili>.
Current version:1.3.8.17(34fe8ef)
Latest stable version:1.3.8
The login is successfully verified.
Favorites ID:113096677
Favorites title :噢噢噢
Creator's name :雨乃哟
。省略
。省略
。省略
Please enter the number of the video you want to choose (You can use "," to separate each two numbers. Use "-" to separate each two numbers to select a range.(e.g. 1-25) If you want to select all videos, please enter "a".):a
-bash: a: command not found
[10]+  Stopped                 python3 start.py -i https://space.bilibili.com/3904677/favlist?fid=113096677‘
- 输入python3 start.py -i https://space.bilibili.com/3904677/favlist?fid=113096677&ftype=create
同样返回command not found
`root@debian:/home/download/Bilibili/bili# python3 start.py -i https://space.bilibili.com/3904677/favlist?fid=113096677&ftype=create
[9] 1758
root@debian:/home/download/Bilibili/bili#     bili  Copyright (C) 2019-2021  lifegpc
    This program comes with ABSOLUTELY NO WARRANTY; for details type `show w'.
    This is free software, and you are welcome to redistribute it
    under certain conditions; type `show c' for details.
    You can find the source code on <https://github.com/lifegpc/bili>.
Current version:1.3.8.17(34fe8ef)
Latest stable version:1.3.8
The login is successfully verified.
Favorites ID:113096677
Favorites title :噢噢噢
Creator's name :雨乃哟
UID：3904677
Create time :2017-04-18 12:59:00
Create time:2019-01-25 07:38:12
Video count :15
Video 1 :
AV number :56376267
BV number :BV1J4411u7Wz
Title :【雨❀竹❀音❀原❀酥】IZONE-Violeta  ❀  隐隐约约 陷入其中
。省略
。省略
。省略
Favorites time :2017-05-13 16:27:48
Please enter the number of the video you want to choose (You can use "," to separate each two numbers. Use "-" to separate each two numbers to select a range.(e.g. 1-25) If you want to select all videos, please enter "a".):a
-bash: a: command not found
[9]+  Stopped                 python3 start.py -i https://space.bilibili.com/3904677/favlist?fid=113096677`

- ### 环境2 windows10
- 使用带变量的下载命令能够下载视频，但是下载方式-d 4参数无效，仍需对每个视频选择下载方式
`C:\Users\LTSC\AppData\Roaming\bili>start.exe -i https://space.bilibili.com/3904677/favlist?fid=113096677&ftype=create -d 4 -p a --ym --yac --ndm --yad --yr --yf --mc avc --ar --ax 2 --as 5 --ak 20 --ab --fa prealloc --nsv --yma --ms 0 --yna -o D:\Bilibili --naf --nslt --nte --nbd --cad --bp --nin --nmt --uc --ass --dmp --vf mkv
    bili  Copyright (C) 2019-2021  lifegpc
    This program comes with ABSOLUTELY NO WARRANTY; for details type `show w'.
    This is free software, and you are welcome to redistribute it
    under certain conditions; type `show c' for details.
    你可以在<https://github.com/lifegpc/bili>上找到源代码。
当前版本：1.3.8.17(34fe8ef)
最新稳定版本：1.3.8
登录校验成功！
收藏夹ID：113096677
收藏夹标题：噢噢噢
创建者名字：雨乃哟
UID：3904677
创建时间：2017-04-18 12:59:00
创建时间：2019-01-25 07:38:12
视频数量：15
视频1：
AV号：56376267
BV号：BV1J4411u7Wz
标题：【雨❀竹❀音❀原❀酥】IZONE-Violeta  ❀  隐隐约约 陷入其中
UP主名称：夏酥酥_
收藏时间：2019-06-22 11:46:31
视频2：
AV号：56374391
BV号：BV1J4411u7h1
标题：【花酱&雨乃&Killer&雾奈】Kill This Love❤BLACKPINK
UP主名称：雾奈哟
。省略
。省略
。省略
请输入你想下载的视频编号（每两个编号间用,隔开，全部下载可输入a，可以使用-分开两个数字以选择一个范围（例如：1-25））：a
您全选了所有视频
登录校验成功！
AV号：56376267
BV号：BV1J4411u7Wz
分P数：1
标题：【雨❀竹❀音❀原❀酥】IZONE-Violeta  ❀  隐隐约约 陷入其中
发布时间：2019-06-22 12:00:00
创建时间：2019-06-22 12:00:12
描述：经过了3天的排练、编队形和紫教官的严格军训，终于把这支舞肝出来了！34度的天在阳光下面晒到神志不清也值了！！！希望观 众姥爷能给一个三连呀！
跟小仙女们一起录舞敲开心的！都辛苦了！以后还要疯狂约舞！！！

摄影：阿斯
后期：雨乃（@雨乃哟） 阿斯
出镜：雨乃（@雨乃哟）
          山竹（@山竹不吃山大竹）
          弥音音（@弥音音ww）
          杯杯  (@冢原野子)
          夏酥酥（原PO）
UP主信息：
UID：4568488
名字：夏酥酥_
分P信息：
第1P：
CID：98515762
分P名：VIOLETA
请输入你要下载的方式：
1.当前弹幕下载
2.全弹幕下载（可能需要大量时间）
3.视频下载
4.当前弹幕+视频下载
5.全弹幕+视频下载
6.仅字幕下载
7.仅封面图片下载
8.仅音频下载4
1P下载完成
视频轨：
画质：高清 1080P60(1920x1080,avc1.64002A,50fps)
文件大小：69.06M(72417475B,5828.95kbps)
音频轨：
ID：30280
文件大小：3873.52K(3966486B,319.27kbps)
正在开始下载第1个文件，共2个文件。
单文件最大5个连接，单个服务器最大3个连接，文件分片大小20M，预分配方式为prealloc
01/19 22:48:49 [NOTICE] Downloading 1 item(s)
01/19 22:48:49 [NOTICE] Allocating disk space. Use --file-allocation=none to disable it. See --file-allocation option in man page for more details.
[#0ebb59 59MiB/69MiB(86%) CN:1 DL:4.8MiB ETA:1s]
01/19 22:49:01 [NOTICE] Download complete: D:/Bilibili/【雨❀竹❀音❀原❀酥】IZONE-Violeta  ❀  隐隐约约 陷入其中(高清 1080P60,avc1.64002A).m4s
Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
0ebb59|OK  |   5.8MiB/s|D:/Bilibili/【雨❀竹❀音❀原❀酥】IZONE-Violeta  ❀  隐隐约约 陷入其中(高清 1080P60,avc1.64002A).m4s
Status Legend:
(OK):download completed.
正在开始下载第2个文件，共2个文件。
单文件最大5个连接，单个服务器最大3个连接，文件分片大小20M，预分配方式为prealloc
01/19 22:49:01 [NOTICE] Downloading 1 item(s)
01/19 22:49:01 [NOTICE] Download complete: D:/Bilibili/【雨❀竹❀音❀原❀酥】IZONE-Violeta  ❀  隐隐约约 陷入其中(30280).m4s
Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
20c508|OK  |    11MiB/s|D:/Bilibili/【雨❀竹❀音❀原❀酥】IZONE-Violeta  ❀  隐隐约约 陷入其中(30280).m4s

Status Legend:
(OK):download completed.
封面图片"D:\Bilibili/【雨❀竹❀音❀原❀酥】IZONE-Violeta  ❀  隐隐约约 陷入其中.jpg"下载完成。
使用ffmpeg合并文件。
ffmpeg version 4.3.1-2020-11-08-full_build-www.gyan.dev Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10.2.0 (Rev3, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'D:\Bilibili/【雨❀竹❀音❀原❀酥】IZONE-Violeta  ❀  隐隐约约 陷入其中(高清 1080P60,avc1.64002A).m4s':
  Metadata:
    major_brand     : iso5
    minor_version   : 1
    compatible_brands: avc1iso5dsmsmsixdash
    encoder         : Lavf57.71.100
    description     : Packed by Bilibili XCoder v2.0.2
  Duration: 00:01:39.30, start: 0.000000, bitrate: 5834 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080, 263 kb/s, 50 fps, 50 tbr, 16k tbn, 100 tbc (default)
    Metadata:
      handler_name    : VideoHandler
Input #1, mov,mp4,m4a,3gp,3g2,mj2, from 'D:\Bilibili/【雨❀竹❀音❀原❀酥】IZONE-Violeta  ❀  隐隐约约 陷入其中(30280).m4s':
  Metadata:
    major_brand     : iso5
    minor_version   : 1
    compatible_brands: avc1iso5dsmsmsixdash
    encoder         : Lavf57.71.100
    description     : Packed by Bilibili XCoder v2.0.2
  Duration: 00:01:39.39, start: 0.040000, bitrate: 319 kb/s
    Stream #1:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 15 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Input #2, ffmetadata, from 'Temp/56376267_1611067743_metadata.txt':
  Metadata:
    title           : 【雨❀竹❀音❀原❀酥】IZONE-Violeta  ❀  隐隐约约 陷入其中 - VIOLETA
    description     : 经过了3天的排练、编队形和紫教官的严格军训，终于把这支舞肝出来了！34度的天在阳光下面晒到神志不清也 值了！！！希望观众姥爷能给一个三连呀！
                    : 跟小仙女们一起录舞敲开心的！都辛苦了！以后还要疯狂约舞！！！
                    :
                    : 摄影：阿斯
                    : 后期：雨乃（@雨乃哟） 阿斯
                    : 出镜：雨乃（@雨乃哟）
                    :           山竹（@山竹不吃山大竹）
                    :           弥音音（@弥音音ww）
                    :           杯杯  (@冢原野子)
                    :           夏酥酥（原PO）
    aid             : 56376267
    bvid            : BV1J4411u7Wz
    cid             : 98515762
    atitle          : 【雨❀竹❀音❀原❀酥】IZONE-Violeta  ❀  隐隐约约 陷入其中
    pubdate         : 2019-06-22 12:00:00
    ctime           : 2019-06-22 12:00:12
    uid             : 4568488
    artist          : 夏酥酥_
    author          : 夏酥酥_
    p               : 1P/1P
    part            : VIOLETA
    vq              : 高清 1080P60,avc1.64002A
    aq              : 30280
    purl            : https://www.bilibili.com/video/av56376267
    tags            : 爵士舞,翻跳,街舞,明星舞蹈,舞蹈
  Duration: N/A, start: 0.000000, bitrate: N/A
Output #0, matroska, to 'D:\Bilibili/【雨❀竹❀音❀原❀酥】IZONE-Violeta  ❀  隐隐约约 陷入其中.mkv':
  Metadata:
    title           : 【雨❀竹❀音❀原❀酥】IZONE-Violeta  ❀  隐隐约约 陷入其中 - VIOLETA
    description     : 经过了3天的排练、编队形和紫教官的严格军训，终于把这支舞肝出来了！34度的天在阳光下面晒到神志不清也 值了！！！希望观众姥爷能给一个三连呀！
                    : 跟小仙女们一起录舞敲开心的！都辛苦了！以后还要疯狂约舞！！！
                    :
                    : 摄影：阿斯
                    : 后期：雨乃（@雨乃哟） 阿斯
                    : 出镜：雨乃（@雨乃哟）
                    :           山竹（@山竹不吃山大竹）
                    :           弥音音（@弥音音ww）
                    :           杯杯  (@冢原野子)
                    :           夏酥酥（原PO）
    aid             : 56376267
    bvid            : BV1J4411u7Wz
    cid             : 98515762
    atitle          : 【雨❀竹❀音❀原❀酥】IZONE-Violeta  ❀  隐隐约约 陷入其中
    pubdate         : 2019-06-22 12:00:00
    ctime           : 2019-06-22 12:00:12
    uid             : 4568488
    artist          : 夏酥酥_
    author          : 夏酥酥_
    p               : 1P/1P
    part            : VIOLETA
    vq              : 高清 1080P60,avc1.64002A
    aq              : 30280
    purl            : https://www.bilibili.com/video/av56376267
    tags            : 爵士舞,翻跳,街舞,明星舞蹈,舞蹈
    encoder         : Lavf58.45.100
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x1080, q=2-31, 263 kb/s, 50 fps, 50 tbr, 1k tbn, 16k tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) ([255][0][0][0] / 0x00FF), 48000 Hz, stereo, fltp, 15 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
    Stream #0:2: Attachment: none
    Metadata:
      filename        : 【雨❀竹❀音❀原❀酥】IZONE-Violeta  ❀  隐隐约约 陷入其中.jpg
      mimetype        : image/jpeg
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #1:0 -> #0:1 (copy)
  File D:\Bilibili/【雨❀竹❀音❀原❀酥】IZONE-Violeta  ❀  隐隐约约 陷入其中.jpg -> Stream #0:2
Press [q] to stop, [?] for help
frame= 4965 fps=0.0 q=-1.0 Lsize=   75297kB time=00:01:39.35 bitrate=6208.7kbits/s speed= 349x
video:70678kB audio:3851kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.030379%
合并完成！
登录校验成功！
AV号：56374391
BV号：BV1J4411u7h1
分P数：1
标题：【花酱&雨乃&Killer&雾奈】Kill This Love❤BLACKPINK
发布时间：2019-06-22 12:00:00
创建时间：2019-06-22 02:55:03
描述：原创：AV48761639
音源：BLACKPINK
ROSE位：花酱
JENNIE位：雨乃
LISA位：Killer
JISOO位：雾奈
摄影：@阿斯Astyon
后期：雾奈

终于赶在雨乃和花酱回家前填坑了！！！大概是最晚翻跳吧，不是很齐呜呜呜！希望大家喜欢！
UP主信息：
UID：6844293
名字：雾奈哟
分P信息：
第1P：
CID：98510871
分P名：KIIL THIS LOVE最终
请输入你要下载的方式：
1.当前弹幕下载
2.全弹幕下载（可能需要大量时间）
3.视频下载
4.当前弹幕+视频下载
5.全弹幕+视频下载
6.仅字幕下载
7.仅封面图片下载
8.仅音频下载`

- ## 总结
目前在debian10系统中使用py脚本无法使用命令下载，输入信息会返回“command not found”，例如“-bash: -d: command not found”
windows系统使用exe版能够正常下载，但是下载方式-d参数传递失败

**Comment by orangeff** [comment]
log文件
[windows10.log](https://github.com/lifegpc/bili/files/5836690/windows10.log)
[debian10-command2.log](https://github.com/lifegpc/bili/files/5836691/debian10-command2.log)
[debian10-command1.log](https://github.com/lifegpc/bili/files/5836692/debian10-command1.log)

**Comment by lifegpc** [comment]
你输入的命令行有问题，请使用双引号将URL括起来，&是特殊字符。

**Comment by lifegpc** [comment]
> 你输入的命令行有问题，请使用双引号将URL括起来，&是特殊字符。

比如说`python3 start.py -i "https://space.bilibili.com/3904677/favlist?fid=113096677&ftype=create" -d 4`

**Comment by orangeff** [comment]
> > 你输入的命令行有问题，请使用双引号将URL括起来，&是特殊字符。
> 
> 比如说`python3 start.py -i "https://space.bilibili.com/3904677/favlist?fid=113096677&ftype=create" -d 4`

非常感谢，目前问题已解决。不过出现了一个新问题
下载过程中如果调用了aria2则会报错
`正在开始下载第2个文件，共2个文件。
单文件最大5个连接，单个服务器最大2个连接，文件分片大小20M，预分配方式为trunc
aria2c: unrecognized option '--async-dns=true'
Usage: aria2c [OPTIONS] [URI | MAGNET | TORRENT_FILE | METALINK_FILE]...
See 'aria2c -h'.
`
我已经依次切换了三个异步DNS选项，均无效果，使用自带的下载器则不会出现问题
[FAV113096677_1611073847.log](https://github.com/lifegpc/bili/files/5837283/FAV113096677_1611073847.log)

**Comment by lifegpc** [comment]
> > > 你输入的命令行有问题，请使用双引号将URL括起来，&是特殊字符。
> > 
> > 
> > 比如说`python3 start.py -i "https://space.bilibili.com/3904677/favlist?fid=113096677&ftype=create" -d 4`
> 
> 非常感谢，目前问题已解决。不过出现了一个新问题
> 下载过程中如果调用了aria2则会报错
> `正在开始下载第2个文件，共2个文件。 单文件最大5个连接，单个服务器最大2个连接，文件分片大小20M，预分配方式为trunc aria2c: unrecognized option '--async-dns=true' Usage: aria2c [OPTIONS] [URI | MAGNET | TORRENT_FILE | METALINK_FILE]... See 'aria2c -h'. `
> 我已经依次切换了三个异步DNS选项，均无效果，使用自带的下载器则不会出现问题
> [FAV113096677_1611073847.log](https://github.com/lifegpc/bili/files/5837283/FAV113096677_1611073847.log)

也许你需要自己编译一个aria2c，新版本我记得有该选项，我自己在ubuntu编译的新版本有该参数。(apt安装的版本也有

**Comment by orangeff** [comment]
> > > > 你输入的命令行有问题，请使用双引号将URL括起来，&是特殊字符。
> > > 
> > > 
> > > 比如说`python3 start.py -i "https://space.bilibili.com/3904677/favlist?fid=113096677&ftype=create" -d 4`
> > 
> > 
> > 非常感谢，目前问题已解决。不过出现了一个新问题
> > 下载过程中如果调用了aria2则会报错
> > `正在开始下载第2个文件，共2个文件。 单文件最大5个连接，单个服务器最大2个连接，文件分片大小20M，预分配方式为trunc aria2c: unrecognized option '--async-dns=true' Usage: aria2c [OPTIONS] [URI | MAGNET | TORRENT_FILE | METALINK_FILE]... See 'aria2c -h'. `
> > 我已经依次切换了三个异步DNS选项，均无效果，使用自带的下载器则不会出现问题
> > [FAV113096677_1611073847.log](https://github.com/lifegpc/bili/files/5837283/FAV113096677_1611073847.log)
> 
> 也许你需要自己编译一个aria2c，新版本有该选项，我自己在ubuntu编译的新版本有该参数。(apt安装的版本也有

好的，感谢指导，我就先用自带的吧，速度也还不错。另外你有赞助的链接吗？想支持一下
