### ISSUE TITLE
两个BUG:Download aborted 以及 获取文件大小失败

### ISSUE THREAD

**Issue by 553627045** [lifegpc/bili#73]
关键词:
[ERROR] CUID#7 - Download aborted.

Exception: [AbstractCommand.cc:351] errorCode=19

Enter command: <target>|all <time>|-1 <command>[ <argument>]

Parse error, at least 3 arguments were expected, only 0 given in string ' wwww     '
获取文件大小失败。尝试重新获取……

[bug.log](https://github.com/lifegpc/bili/files/6134419/bug.log)

**Comment by lifegpc** [comment]
第一个DNS服务器连接超时（你网络问题

**Comment by lifegpc** [comment]
第二个请上传log文件夹里的对应av号的log，你发的log没有更多有用的信息

**Comment by 553627045** [comment]
[AV371555674_1615616592_2.log](https://github.com/lifegpc/bili/files/6134526/AV371555674_1615616592_2.log)
[Uploading AV371555674_1615616592.log…]()

**Comment by lifegpc** [comment]
第二个问题依旧是DNS服务器问题（还是网络问题
`<urllib3.connection.HTTPSConnection object at 0x000002BCAE2CA208>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'`
getaddrinfo是获取IP的函数。
建议你使用一个稳定的DNS服务器
