### ISSUE TITLE
macos上aria2c报错

### ISSUE THREAD

**Issue by PiraticAshin** [lifegpc/bili#96]
问题:aria2c报错:aria2c: unrecognized option `--async-dns=true'
应该和异步dns选项有关系,事实上不论是关还是开都会报错

1. aria2通过homebrew安装
2. 在m1芯片mac和x64虚拟机上都会报错
<img width="499" alt="截屏2021-06-29 14 14 58" src="https://user-images.githubusercontent.com/36768731/123746591-6c891b80-d8e4-11eb-94ad-75f7ad78b075.png">

[
[AV673762801_1624947077.log](https://github.com/lifegpc/bili/files/6731100/AV673762801_1624947077.log)
](url)

**Comment by lifegpc** [comment]
看起来是你使用的aria2c不支持这个参数

**Comment by PiraticAshin** [comment]
> 看起来是你使用的aria2c不支持这个参数

确实,官方自己做的OS X的dwg包安了能正常用,就很离谱 但m1嘛,嗯
