### ISSUE TITLE
能下载最新的杜比全景声的视频吗？

### ISSUE THREAD

**Issue by yinzhefuyun** [lifegpc/bili#99]
能下载最新的杜比全景声的视频吗？例如：https://www.bilibili.com/video/BV1oq4y1S7T1

**Comment by lifegpc** [comment]
现在程序基于的几乎都是网页端API（重构版这点也不会变）。网页端上由于浏览器几乎缺乏EAC支持，所以应该无法解析到。（Edge是少数能支持EAC的浏览器，但B站应该不会专门为edge做支持
